import { execSync } from "node:child_process";
import { createHash } from "node:crypto";
import react from "@vitejs/plugin-react";
import type { Plugin } from "vite";
import { defineConfig } from "vitest/config";

// The app is served at /next/ next to the legacy page (/) during the
// transition. In dev and preview, /api goes to a local PocketBase.
const PB_LOCAL = process.env.PB_URL || "http://127.0.0.1:8096";
const proxy = { "/api": { target: PB_LOCAL, changeOrigin: true } };

// Offline shell: writes sw.js with the exact list of built files, so the
// service worker (scope /next/) precaches index + hashed assets.
function serviceWorker(): Plugin {
  return {
    name: "trip-sw",
    apply: "build",
    generateBundle(_, bundle) {
      const files = Object.keys(bundle).filter((f) => !f.endsWith(".map") && f !== "sw.js").sort();
      const version = createHash("sha256").update(files.join("\n")).digest("hex").slice(0, 10);
      const shell = ["./", ...files.filter((f) => f !== "index.html")];
      this.emitFile({ type: "asset", fileName: "sw.js", source: swSource(version, shell) });
    },
  };
}

function swSource(version: string, shell: string[]): string {
  return `// Generated by app/vite.config.ts. Scope: /next/. API calls are never cached;
// the app keeps its own snapshot and write queue.
const PREFIX = "trip-next-";
const CACHE = PREFIX + ${JSON.stringify(version)};
const SHELL = ${JSON.stringify(shell)};
const SCOPE = new URL("./", self.location).pathname;

self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(SHELL)).then(() => self.skipWaiting()));
});
self.addEventListener("activate", (e) => {
  e.waitUntil(caches.keys()
    .then((keys) => Promise.all(keys.filter((k) => k.startsWith(PREFIX) && k !== CACHE).map((k) => caches.delete(k))))
    .then(() => self.clients.claim()));
});
const put = (req, res) => {
  if (res.ok || res.type === "opaque") {
    const copy = res.clone();
    caches.open(CACHE).then((c) => c.put(req, copy)).catch(() => {});
  }
  return res;
};
self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  const isFont = /fonts\\.(googleapis|gstatic)\\.com$/.test(url.hostname);
  if (!isFont && (url.origin !== self.location.origin || !url.pathname.startsWith(SCOPE))) return;
  if (url.pathname.includes("/api/")) return;
  if (req.mode === "navigate") {
    // Network first, so a deploy shows up on the next open; the shell as fallback.
    e.respondWith(fetch(req).then((res) => put(SCOPE, res)).catch(() => caches.match(SCOPE)));
    return;
  }
  if (url.pathname.startsWith(SCOPE + "assets/")) {
    // Hashed file names never change: cache first.
    e.respondWith(caches.match(req).then((hit) => hit || fetch(req).then((res) => put(req, res))));
    return;
  }
  e.respondWith(fetch(req).then((res) => put(req, res)).catch(() => caches.match(req, { ignoreSearch: true })));
});
`;
}

// Short commit (or build time) shown in «Ещё», to tell which build a phone runs.
const BUILD = (() => {
  try {
    return execSync("git rev-parse --short HEAD", { stdio: ["ignore", "pipe", "ignore"] }).toString().trim();
  } catch {
    return new Date().toISOString().slice(0, 16).replace("T", " ");
  }
})();

export default defineConfig({
  base: "/next/",
  define: { __BUILD__: JSON.stringify(BUILD) },
  plugins: [react(), serviceWorker()],
  server: { port: 5196, strictPort: true, proxy },
  preview: { port: 5197, strictPort: true, proxy },
  build: {
    target: "es2022",
    sourcemap: false,
    assetsInlineLimit: 0,
    // lab.html: drawer comparison page for phone testing (not linked in the app).
    rollupOptions: { input: { index: "index.html", lab: "lab.html" } },
  },
  test: { environment: "node", include: ["src/**/*.test.ts"] },
});
