// Builds dist/ for the Worker's static assets (wrangler.jsonc -> assets.directory):
//   dist/           = app/dist (React app, Vite base "/")
//   dist/_headers   = cache rules
//   dist/_redirects = retired addresses (/next/, /old/, /lab) -> /
// Run via `npm run build` (after the app build).
import { cpSync, existsSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const app = join(root, "app", "dist");
const out = join(root, "dist");

if (!existsSync(join(app, "index.html"))) {
  console.error("assemble: app/dist/index.html is missing, run the app build first");
  process.exit(1);
}

rmSync(out, { recursive: true, force: true });
cpSync(app, out, { recursive: true });

writeFileSync(join(out, "_headers"), `# Generated by scripts/assemble.mjs
/
  Cache-Control: no-cache
/index.html
  Cache-Control: no-cache
/sw.js
  Cache-Control: no-cache
/assets/*
  Cache-Control: public, max-age=31536000, immutable
`);

// The browser keeps the #key fragment across the redirect.
writeFileSync(join(out, "_redirects"), `# Generated by scripts/assemble.mjs
/next /  301
/next/ /  301
/next/* /  301
/old /  301
/old/ /  301
/old/* /  301
/lab /  301
/lab.html /  301
`);

console.log("assemble: dist/ = app/dist at /");
