// Builds dist/ for the Worker's static assets (wrangler.jsonc -> assets.directory):
//   dist/           = app/dist (React app, Vite base "/")
//   dist/old/       = web/ as is (legacy one-file page, kept as a fallback)
//   dist/_headers   = cache rules for both
//   dist/_redirects = /next/* (the app's transition address) -> /
// Run via `npm run build` (after the app build).
import { cpSync, existsSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const web = join(root, "web");
const app = join(root, "app", "dist");
const out = join(root, "dist");

if (!existsSync(join(app, "index.html"))) {
  console.error("assemble: app/dist/index.html is missing, run the app build first");
  process.exit(1);
}

rmSync(out, { recursive: true, force: true });
cpSync(app, out, { recursive: true });
cpSync(web, join(out, "old"), { recursive: true });
rmSync(join(out, "old", "_headers"), { force: true });

writeFileSync(join(out, "_headers"), `# Generated by scripts/assemble.mjs
/
  Cache-Control: no-cache
/index.html
  Cache-Control: no-cache
/sw.js
  Cache-Control: no-cache
/assets/*
  Cache-Control: public, max-age=31536000, immutable
/old/
  Cache-Control: no-cache
/old/index.html
  Cache-Control: no-cache
/old/sw.js
  Cache-Control: no-cache
`);

// The browser keeps the #key fragment across the redirect.
writeFileSync(join(out, "_redirects"), `# Generated by scripts/assemble.mjs
/next /  301
/next/ /  301
/next/* /  301
`);

console.log("assemble: dist/ = app/dist at /, web/ at /old/");
